name: cbc_calc
description: "Simple Calculator App for use in a clinical Hematology Lab to quickly Re-Calculate MCHC and other Erythrocyte-Indices in Samples where MCHC > 36,5 "
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
flutter_icons:
  android: true
  ios: false
  image_path: "assets/icon.png"